### ISSUE TITLE
3DMark05 crashes

### ISSUE THREAD

**Issue by gurketsky** [chrisbmr/wine#1]
Steps to reproduce:
1. get 3DMark 05: http://www.futuremark.com/support/downloads
2. install
3. run wine 3DMark05.exe -nosysteminfo
4. crashes after the first benchmark

The corresponding unpatched (original) wine doesn't crash. The only differences are the patches from here. The new feature (gallium-nine) isn't even used.

Backtrace:
wine: Unhandled page fault on read access to 0x7d925744 at address 0x7d925744 (thread 0009), starting debugger...
Unhandled exception: page fault on read access to 0x7d925744 in 32-bit code (0x7d925744).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7d925744 ESP:0032cfdc EBP:0032d008 EFLAGS:00010206(  R- --  I   - -P- )
 EAX:7d925744 EBX:7e8f4000 ECX:00000000 EDX:00000003
 ESI:0032d08c EDI:000300c6
Stack dump:
0x0032cfdc:  7e8b6e1a 000300c6 00000024 00000000
0x0032cfec:  0032d830 00000204 7e7aa000 0032d020
0x0032cffc:  7e8f4000 0032d08c 000300c6 0032d058
0x0032d00c:  7e8b7556 7d925744 000300c6 00000024
0x0032d01c:  00000000 0032d830 00000000 0032d04c
0x0032d02c:  7dc07fec 00121884 00000000 7dbbbed5
Backtrace:
=>0 0x7d925744 (0x0032d008)
  1 0x7e8b7556 call_window_proc+0x55(hwnd=0x300c6, msg=0x24, wp=0, lp=0x32d830, result=0x32d08c, arg=0x7d925744) [/mnt/raid0/software/wine/nine_build/dlls/user32/../../../nine.git/dlls/user32/winproc.c:244] in user32 (0x0032d058)
  2 0x7e8b9d8b CallWindowProcA+0x5a(func=0x7d925744, hwnd=0x300c6, msg=0x24, wParam=0, lParam=0x32d830) [/mnt/raid0/software/wine/nine_build/dlls/user32/../../../nine.git/dlls/user32/winproc.c:955] in user32 (0x0032d0a4)
  3 0x7c173adb in mfc71 (+0x33ada) (0x0032d118)
  4 0x7e8b6e1a WINPROC_wrapper+0x19() in user32 (0x0032d148)
  5 0x7e8b7556 call_window_proc+0x55(hwnd=0x300c6, msg=0x24, wp=0, lp=0x32d830, result=0x32d6d8, arg=0x7c173a6e) [/mnt/raid0/software/wine/nine_build/dlls/user32/../../../nine.git/dlls/user32/winproc.c:244] in user32 (0x0032d198)
  6 0x7e8b7a71 WINPROC_CallProcWtoA+0x1a0(callback=<is not available>, hwnd=<is not available>, msg=0x24, wParam=0, lParam=0x32d830, result=0x32d6d8, arg=0x7c173a6e) [/mnt/raid0/software/wine/nine_build/dlls/user32/../../../nine.git/dlls/user32/winproc.c:727] in user32 (0x0032d658)
  7 0x7e8b9cc6 WINPROC_call_window+0x195(hwnd=0x300c6, msg=0x24, wParam=0, lParam=0x32d830, result=0x32d6d8, unicode=0x1, mapping=2123043339) [/mnt/raid0/software/wine/nine_build/dlls/user32/../../../nine.git/dlls/user32/winproc.c:902] in user32 (0x0032d6a8)
  8 0x7e878cdd call_window_proc+0x8c(hwnd=0x300c6, msg=0x24, wparam=0, lparam=0x32d830, unicode=0x1, same_thread=0x1, mapping=2123043339) [/mnt/raid0/software/wine/nine_build/dlls/user32/../../../nine.git/dlls/user32/message.c:2222] in user32 (0x0032d708)
  9 0x7e880486 send_message+0x1f5(info=0x32d794, res_ptr=0x32d790, unicode=0x1) [/mnt/raid0/software/wine/nine_build/dlls/user32/../../../nine.git/dlls/user32/message.c:3214] in user32 (0x0032d778)
  10 0x7e880719 SendMessageW+0x58(hwnd=0x300c6, msg=0x24, wparam=0, lparam=0x32d830) [/mnt/raid0/software/wine/nine_build/dlls/user32/../../../nine.git/dlls/user32/message.c:3408] in user32 (0x0032d7c8)
  11 0x7e8b126b WINPOS_GetMinMaxInfo+0x19a(hwnd=0x300c6, maxSize=0x32d924, maxPos=0x32d92c, minTrack=0x32d934, maxTrack=0x32d968) [/mnt/raid0/software/wine/nine_build/dlls/user32/../../../nine.git/dlls/user32/winpos.c:793] in user32 (0x0032d898)
  12 0x7e8ad30c WIN_CreateWindowEx+0x63b(cs=0x32da60, className="FAKED3D9WINDOW", module=(nil), unicode=0) [/mnt/raid0/software/wine/nine_build/dlls/user32/../../../nine.git/dlls/user32/win.c:1560] in user32 (0x0032da18)
  13 0x7e8a6e5f CreateWindowExA+0x189(exStyle=<couldn't compute location>, className=<couldn't compute location>, windowName=<couldn't compute location>, style=<couldn't compute location>, x=<couldn't compute location>, y=<couldn't compute location>, width=<couldn't compute location>, height=<couldn't compute location>, parent=<couldn't compute location>, menu=<couldn't compute location>, instance=<couldn't compute location>, data=<couldn't compute location>) [/mnt/raid0/software/wine/nine_build/dlls/user32/../../../nine.git/dlls/user32/win.c:1711] in user32 (0x0032dca8)
  14 0x7d1a57b7 d3dadapter9_new+0x1b6(ex=0, ppOut=0x32dd4c) [/mnt/raid0/software/wine/nine_build/dlls/d3d9/../../../nine.git/dlls/d3d9/d3dadapter9.c:801] in d3d9 (0x0032dd18)
  15 0x7d1a300f Direct3DCreate9+0x49(sdk_version=<couldn't compute location>) [/mnt/raid0/software/wine/nine_build/dlls/d3d9/../../../nine.git/dlls/d3d9/d3d9_main.c:84] in d3d9 (0x0032dd68)
0x7d925744: -- no code accessible --
Modules:
Module  Address         Debug info  Name (104 modules)
PE    330000-  38b000   Deferred        exporter
PE    400000-  6f9000   Export          3dmark05
PE    700000-  77b000   Deferred        msvcp71
PE  10000000-10059000   Deferred        si3
ELF 490b3000-490bc000   Deferred        librt.so.1
ELF 490be000-490c6000   Deferred        libffi.so.6
ELF 49255000-49278000   Deferred        libselinux.so.1
ELF 4945e000-494c6000   Deferred        libpcre.so.1
ELF 49693000-496b0000   Deferred        libgcc_s.so.1
ELF 49971000-4998a000   Deferred        libxcb-glx.so.0
ELF 499e9000-499ef000   Deferred        libxcb-dri2.so.0
ELF 49d8e000-49da1000   Deferred        libudev.so.1
ELF 49de4000-49e22000   Deferred        libglapi.so.0
ELF 4a22c000-4a230000   Deferred        libxdamage.so.1
ELF 4a752000-4a7c9000   Deferred        libgl.so.1
ELF 4a7d1000-4a7d4000   Deferred        libx11-xcb.so.1
ELF 7a21b000-7b800000   Deferred        libllvm-3.3.so
ELF 7b800000-7ba5a000   Deferred        kernel32<elf>
  -PE  7b810000-7ba5a000   \               kernel32
ELF 7bc00000-7bcd6000   Deferred        ntdll<elf>
  -PE  7bc10000-7bcd6000   \               ntdll
ELF 7bf00000-7bf04000   Deferred        <wine-loader>
PE  7c140000-7c243000   Export          mfc71
PE  7c340000-7c396000   Deferred        msvcr71
ELF 7c5b7000-7cdc8000   Deferred        r600_dri.so
ELF 7d18e000-7d1ce000   Dwarf           d3d9<elf>
  -PE  7d190000-7d1ce000   \               d3d9
ELF 7d1ce000-7d210000   Deferred        usp10<elf>
  -PE  7d1d0000-7d210000   \               usp10
ELF 7d3b6000-7d3bc000   Deferred        libtxc_dxtn.so
ELF 7d3bc000-7d3ca000   Deferred        libdrm_radeon.so.1
ELF 7d4b5000-7d896000   Deferred        libd3dadapter9.so.0
ELF 7d953000-7d989000   Deferred        uxtheme<elf>
  -PE  7d960000-7d989000   \               uxtheme
ELF 7d989000-7d995000   Deferred        libxcursor.so.1
ELF 7d995000-7d9a6000   Deferred        libxi.so.6
ELF 7d9a6000-7d9ac000   Deferred        libxfixes.so.3
ELF 7d9ac000-7d9b0000   Deferred        libxcomposite.so.1
ELF 7d9b0000-7d9bb000   Deferred        libxrandr.so.2
ELF 7d9bb000-7d9c6000   Deferred        libxrender.so.1
ELF 7d9c6000-7d9cc000   Deferred        libxxf86vm.so.1
ELF 7d9cc000-7d9d0000   Deferred        libxinerama.so.1
ELF 7d9d0000-7d9d4000   Deferred        libxau.so.6
ELF 7d9d4000-7d9f6000   Deferred        libxcb.so.1
ELF 7d9f6000-7d9fc000   Deferred        libuuid.so.1
ELF 7d9fc000-7db36000   Deferred        libx11.so.6
ELF 7db36000-7db49000   Deferred        libxext.so.6
ELF 7db49000-7db63000   Deferred        libice.so.6
ELF 7db63000-7db6c000   Deferred        libsm.so.6
ELF 7db6f000-7db7c000   Deferred        libdrm.so.2
ELF 7db7c000-7dba1000   Deferred        imm32<elf>
  -PE  7db80000-7dba1000   \               imm32
ELF 7dba3000-7dc3a000   Deferred        winex11<elf>
  -PE  7dbb0000-7dc3a000   \               winex11
ELF 7dc3a000-7dc63000   Deferred        libexpat.so.1
ELF 7dc63000-7dc9f000   Deferred        libfontconfig.so.1
ELF 7dc9f000-7dd40000   Deferred        libfreetype.so.6
ELF 7dd40000-7dd62000   Deferred        libtinfo.so.5
ELF 7dd62000-7dd8a000   Deferred        libncurses.so.5
ELF 7ddc1000-7de0b000   Deferred        dsound<elf>
  -PE  7ddd0000-7de0b000   \               dsound
ELF 7de0b000-7dec4000   Deferred        winmm<elf>
  -PE  7de10000-7dec4000   \               winmm
ELF 7dec4000-7dfc1000   Deferred        opengl32<elf>
  -PE  7dee0000-7dfc1000   \               opengl32
ELF 7dfc1000-7e100000   Deferred        wined3d<elf>
  -PE  7dfd0000-7e100000   \               wined3d
ELF 7e100000-7e175000   Deferred        ddraw<elf>
  -PE  7e110000-7e175000   \               ddraw
ELF 7e175000-7e19c000   Deferred        mpr<elf>
  -PE  7e180000-7e19c000   \               mpr
ELF 7e19c000-7e1b3000   Deferred        libz.so.1
ELF 7e1bf000-7e1ea000   Deferred        msacm32<elf>
  -PE  7e1c0000-7e1ea000   \               msacm32
ELF 7e1ea000-7e265000   Deferred        wininet<elf>
  -PE  7e1f0000-7e265000   \               wininet
ELF 7e265000-7e39a000   Deferred        oleaut32<elf>
  -PE  7e280000-7e39a000   \               oleaut32
ELF 7e39a000-7e41b000   Deferred        rpcrt4<elf>
  -PE  7e3b0000-7e41b000   \               rpcrt4
ELF 7e41b000-7e558000   Deferred        ole32<elf>
  -PE  7e430000-7e558000   \               ole32
ELF 7e558000-7e65f000   Deferred        comctl32<elf>
  -PE  7e560000-7e65f000   \               comctl32
ELF 7e65f000-7e679000   Deferred        version<elf>
  -PE  7e660000-7e679000   \               version
ELF 7e679000-7e6eb000   Deferred        advapi32<elf>
  -PE  7e690000-7e6eb000   \               advapi32
ELF 7e6eb000-7e802000   Deferred        gdi32<elf>
  -PE  7e700000-7e802000   \               gdi32
ELF 7e802000-7e95c000   Dwarf           user32<elf>
  -PE  7e810000-7e95c000   \               user32
ELF 7e95c000-7e9d6000   Deferred        shlwapi<elf>
  -PE  7e970000-7e9d6000   \               shlwapi
ELF 7e9d6000-7ec09000   Deferred        shell32<elf>
  -PE  7e9e0000-7ec09000   \               shell32
ELF 7ef79000-7ef86000   Deferred        libnss_files.so.2
ELF 7ef86000-7efc9000   Deferred        libm.so.6
ELF f73b4000-f73b9000   Deferred        libdl.so.2
ELF f73b9000-f7576000   Deferred        libc.so.6
ELF f7576000-f7590000   Deferred        libpthread.so.0
ELF f75c7000-f777c000   Dwarf           libwine.so.1
ELF f777d000-f779e000   Deferred        ld-linux.so.2
ELF f779e000-f779f000   Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) C:\Programme\Futuremark\3DMark05\3DMark05.exe
    00000009    0 <==
0000000e services.exe
    00000034    0
    0000001c    0
    00000014    0
    00000010    0
    0000000f    0
00000012 winedevice.exe
    0000001b    0
    00000018    0
    00000017    0
    00000013    0
00000019 plugplay.exe
    00000020    0
    0000001f    0
    0000001a    0
00000023 explorer.exe
    00000024    0

**Comment by zhasha** [comment]
I can't reproduce this, however I did find and correct a bug in the window registration code. The fix has been pushed.

Did you replace the following dlls: d3d9.dll.so, gdi32.dll.so, user32.dll.so, wineps.drv.so, and winex11.drv.so in your /usr/lib/wine dir? That error looks a lot like the kind of error I would get when I forgot to replace user32.dll.
I can run the entire demo without issue using wined3d.

**Comment by gurketsky** [comment]
Yeah, the issue is fixed by commit 39e6fd0e2ce1ab64908d671e801300fbfc7d1229.

No, I did not replace those stuff. I did, which should be equivalent:
- git clone
- make an out of tree build (optional, should also work, if you make an in tree build)
- run that wine build (it has already all libs linked correctly, without messing with some symlinks)

Thanks.
