### ISSUE TITLE
Wine fails to create ID3DAdapter9

### ISSUE THREAD

**Issue by tizbac** [chrisbmr/wine#2]
With WINEDEBUG=warn+all i see dri2_create_adapter9 Unabel to create ID3DAdapter9 ( fd=17 ) and it will then switch to opengl
I've built mesa-gallium and wine from your repository under ubuntu 13.10 daily i386 
I've tried recompiling libdrm too from latest tarball , but no luck

**Comment by zhasha** [comment]
Try with WINEDEBUG=+d3d9,+d3dadapter NINE_DEBUG=all

**Comment by tizbac** [comment]
trace:d3d9:DllMain fdwReason=1
trace:d3d9:Direct3DCreate9 sdk_version 0x1f.
Trynative: 1
Native..
trace:d3dadapter:has_d3dadapter Got DRI2 version 1.4
trace:d3dadapter:has_d3dadapter Got XFixes version 5.0
fixme:win:EnumDisplayDevicesW ((null),0,0x32f268,0x00000000), stub!
Dis device
trace:d3dadapter:dri2_create_adapter9 Associated `nouveau' with fd 18 opened from`/dev/dri/card0'
warn:d3dadapter:dri2_create_adapter9 Unable to create ID3DAdapter9 (fd=18)
Failed hdc
fixme:win:EnumDisplayDevicesW ((null),1,0x32f268,0x00000000), stub!
ngroups=0
No available native adapters in system.
trace:d3d9:d3dadapter9_Release 0x13e6d8 decreasing refcount to 0.
Native failed
fixme:win:EnumDisplayDevicesW ((null),0,0x32f218,0x00000000), stub!
Created d3d9 object 0x13bbb0.
trace:d3d9:d3d9_GetAdapterCount iface 0x13bbb0.
trace:d3d9:d3d9_GetDeviceCaps iface 0x13bbb0, adapter 0, device_type 0x1, caps 0x8a24e0.
trace:d3d9:d3d9_GetAdapterModeCount iface 0x13bbb0, adapter 0, format 0x17.
trace:d3d9:d3d9_GetAdapterModeCount iface 0x13bbb0, adapter 0, format 0x16.
trace:d3d9:d3d9_GetAdapterModeCount iface 0x13bbb0, adapter 0, format 0x23.
trace:d3d9:d3d9_GetAdapterDisplayMode iface 0x13bbb0, adapter 0, mode 0x8a24c4.

There are some lines caused by some printf i added to see what function was failing cause for some odd reason before i rebooted WINEDEBUG env variable was being ignored

**Comment by zhasha** [comment]
It looks like you either didn't set NINE_DEBUG=all or you compiled nine without --enable-debug. I can't say anything about what's wrong without output from nine in this case.

**Comment by tizbac** [comment]
i have to pass --enable-debug on mesa configure , do i remembere correctly?

**Comment by zhasha** [comment]
Yes, and then do a full rebuild just to be sure automake didn't screw you

**Comment by tizbac** [comment]
it says nine:drm_create_adapter: Unable to load requested driver

**Comment by zhasha** [comment]
Your drivers aren't in the search path. Configure with --with-gallium-driver-dir="`pwd`/src/gallium/targets/pipe-loader/.libs" for a lazy solution
